module.exports = {
	perfis:{
		ADM:"adm",
		USER:"user"
	},
	cerveja:{
		status:{
			importado:"importado",
			verificado:"verificado",
			pendente:"pendente"
		},
		copos:{
			Goblet:"Cálice",
			Mug:"Caneca",
			Tulip:"Tulipa",
			Stange:"Stange/haste",
			Weizen:"Trigo"
		}
	}
}